Merge jdk
openjdk/valhalla pull request #930
Opened 2023-09-27 12:47 UTC by MrSimms

Merge jdk-22+9

2023-09-27 15:13 UTC, MrSimms commented
/summary Merge jdk-22+9

2023-09-28 18:17 UTC, fparain requested changes

2023-09-29 07:10 UTC, MrSimms commented on src/hotspot/cpu/x86/templateTable_x86.cpp
> +  __ movl(rscratch2, rdx);  // saving flags for is_flat test
Agreed, thanks for the suggested fix.

2023-10-02 07:41 UTC, MrSimms commented
/integrate

2023-10-02 07:50 UTC, closed without merging